version: "3"
services:
  strapi:
    build:
      context: .
      dockerfile: ./dockerfiles/prod/strapi.dockerfile
    restart: always
    working_dir: /var/www/app/
    env_file: .env
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_FILENAME=${DATABASE_FILENAME}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - NODE_ENV=production
    volumes:
      - ./storage:/data/db
    ports:
      - "1337:1337"
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge
