version: "3"
services:
  strapi:
    image: node:18.18.2
    build:
      context: .
      dockerfile: ./dockerfiles/strapi/local.dockerfile
    restart: always
    env_file: .env
    working_dir: /var/www/app/
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./node_modules:/var/www/app/node_modules
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  npm_client:
    image: node:18.18.2
    volumes:
      - ${CLIENT_CONTEXT_PATH}:/var/www/app
    working_dir: /var/www/app
    entrypoint: npm
    networks:
      - biocinema_internal_network

  strapiDB:
    image: postgres:12.0-alpine
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge
