// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface HeroHeaderField {
  title: string;
  description: string;
  cta_button: string;
  main_image: { data: Media };
  secondary_image: { data: Media };
}
export interface HeroHeaderField_Plain {
  title: string;
  description: string;
  cta_button: string;
  main_image: Media_Plain;
  secondary_image: Media_Plain;
}

export interface HeroHeaderField_NoRelations {
  title: string;
  description: string;
  cta_button: string;
  main_image: number;
  secondary_image: number;
}

