// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Company {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    brow?: string;
    slug?: string;
    description?: string;
    logo: { data: Media };
    background_image: { data: Media };
  };
}
export interface Company_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  brow?: string;
  slug?: string;
  description?: string;
  logo: Media_Plain;
  background_image: Media_Plain;
}

export interface Company_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  brow?: string;
  slug?: string;
  description?: string;
  logo: number;
  background_image: number;
}

export interface Company_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  brow?: string;
  slug?: string;
  description?: string;
  logo: AdminPanelRelationPropertyModification<Media_Plain>;
  background_image: AdminPanelRelationPropertyModification<Media_Plain>;
}
