// Interface automatically generated by schemas-to-ts

import { LongAbout } from '../components/long-about/LongAbout';
import { Projects } from '../components/projects/Projects';
import { HeroHeaderField } from '../components/header/HeroHeaderField';
import { Companies } from '../components/companies/Companies';
import { ContactMe } from '../components/about/ContactMe';
import { LayoutSite } from './layout-site';
import { LongAbout_Plain } from '../components/long-about/LongAbout';
import { Projects_Plain } from '../components/projects/Projects';
import { HeroHeaderField_Plain } from '../components/header/HeroHeaderField';
import { Companies_Plain } from '../components/companies/Companies';
import { ContactMe_Plain } from '../components/about/ContactMe';
import { LayoutSite_Plain } from './layout-site';
import { LongAbout_NoRelations } from '../components/long-about/LongAbout';
import { Projects_NoRelations } from '../components/projects/Projects';
import { HeroHeaderField_NoRelations } from '../components/header/HeroHeaderField';
import { Companies_NoRelations } from '../components/companies/Companies';
import { ContactMe_NoRelations } from '../components/about/ContactMe';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Index {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    about_section: any;
    SEO?: any;
    long_about_section: LongAbout;
    projects_section: Projects;
    header_section: HeroHeaderField;
    companies_section: Companies;
    contact_me_section: ContactMe;
    layout_site: { data: LayoutSite };
  };
}
export interface Index_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  about_section: any;
  SEO?: any;
  long_about_section: LongAbout_Plain;
  projects_section: Projects_Plain;
  header_section: HeroHeaderField_Plain;
  companies_section: Companies_Plain;
  contact_me_section: ContactMe_Plain;
  layout_site: LayoutSite_Plain;
}

export interface Index_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  about_section: any;
  SEO?: any;
  long_about_section: LongAbout_NoRelations;
  projects_section: Projects_NoRelations;
  header_section: HeroHeaderField_NoRelations;
  companies_section: Companies_NoRelations;
  contact_me_section: ContactMe_NoRelations;
  layout_site: number;
}

export interface Index_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  about_section: any;
  SEO?: any;
  long_about_section: LongAbout_Plain;
  projects_section: Projects_Plain;
  header_section: HeroHeaderField_Plain;
  companies_section: Companies_Plain;
  contact_me_section: ContactMe_Plain;
  layout_site: AdminPanelRelationPropertyModification<LayoutSite_Plain>;
}
