// Interface automatically generated by schemas-to-ts

import { Layout } from '../components/layout/Layout';
import { Layout_Plain } from '../components/layout/Layout';
import { Layout_NoRelations } from '../components/layout/Layout';

export interface LayoutSite {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    info?: Layout;
  };
}
export interface LayoutSite_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  info?: Layout_Plain;
}

export interface LayoutSite_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  info?: Layout_NoRelations;
}

export interface LayoutSite_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  info?: Layout_Plain;
}
