// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface ProgrammingLanguage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    icon: { data: Media };
    experience?: string;
  };
}
export interface ProgrammingLanguage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  icon: Media_Plain;
  experience?: string;
}

export interface ProgrammingLanguage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  icon: number;
  experience?: string;
}

export interface ProgrammingLanguage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  icon: AdminPanelRelationPropertyModification<Media_Plain>;
  experience?: string;
}
