// Interface automatically generated by schemas-to-ts

import { Media } from '../common/Media';
import { Media_Plain } from '../common/Media';
import { AdminPanelRelationPropertyModification } from '../common/AdminPanelRelationPropertyModification';

export interface Project {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    about?: string;
    subtitle?: string;
    slug: string;
    description?: string;
    icon: { data: Media };
    image: { data: Media };
  };
}
export interface Project_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  about?: string;
  subtitle?: string;
  slug: string;
  description?: string;
  icon: Media_Plain;
  image: Media_Plain;
}

export interface Project_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  about?: string;
  subtitle?: string;
  slug: string;
  description?: string;
  icon: number;
  image: number;
}

export interface Project_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  about?: string;
  subtitle?: string;
  slug: string;
  description?: string;
  icon: AdminPanelRelationPropertyModification<Media_Plain>;
  image: AdminPanelRelationPropertyModification<Media_Plain>;
}
