apiVersion: v1
kind: Service
metadata:
  namespace: portfolio
  name: strapi-cms
spec:
  selector:
    app: strapi-cms
  type: NodePort
  ports:
    - port: 1337
      targetPort: 1337
      nodePort: 30070
