// Interface automatically generated by schemas-to-ts

import { Company } from '../../api/company';
import { Company_Plain } from '../../api/company';

export interface Companies {
  title: string;
  companies: { data: Company[] };
}
export interface Companies_Plain {
  title: string;
  companies: Company_Plain[];
}

export interface Companies_NoRelations {
  title: string;
  companies: number[];
}

