// Interface automatically generated by schemas-to-ts

import { Project } from '../../api/project';
import { Project_Plain } from '../../api/project';

export interface Projects {
  title: string;
  subtitle: string;
  projects: { data: Project[] };
}
export interface Projects_Plain {
  title: string;
  subtitle: string;
  projects: Project_Plain[];
}

export interface Projects_NoRelations {
  title: string;
  subtitle: string;
  projects: number[];
}

