// Interface automatically generated by schemas-to-ts

import { Media } from '../../common/Media';
import { Media_Plain } from '../../common/Media';

export interface About {
  title: string;
  about: string;
  brow: string;
  dev_image: { data: Media };
}
export interface About_Plain {
  title: string;
  about: string;
  brow: string;
  dev_image: Media_Plain;
}

export interface About_NoRelations {
  title: string;
  about: string;
  brow: string;
  dev_image: number;
}

