// Interface automatically generated by schemas-to-ts

export interface ContactMe {
  title: string;
  email_cta: string;
}
export interface ContactMe_Plain {
  title: string;
  email_cta: string;
}

export interface ContactMe_NoRelations {
  title: string;
  email_cta: string;
}

