// Interface automatically generated by schemas-to-ts

import { SocialLink } from '../../api/social-link';
import { SocialLink_Plain } from '../../api/social-link';

export interface ContactMe {
  title: string;
  brow: string;
  social_links: { data: SocialLink[] };
}
export interface ContactMe_Plain {
  title: string;
  brow: string;
  social_links: SocialLink_Plain[];
}

export interface ContactMe_NoRelations {
  title: string;
  brow: string;
  social_links: number[];
}

