// Interface automatically generated by schemas-to-ts

export interface LongAbout {
  title: string;
  content: string;
}
export interface LongAbout_Plain {
  title: string;
  content: string;
}

export interface LongAbout_NoRelations {
  title: string;
  content: string;
}

